# This is a basic workflow that is manually triggered

name: Deploy API to live environment
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
    - name: pull the latest files in docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_UNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          pwd
          #docker exec -it onlinegameV2 echo "I'm inside the container!"
          #docker exec -it onlinegameV2 bash -c "cd online-game-backend;git pull"
          # docker restart onlinegameV2
